### ISSUE TITLE
Lessons component development

### ISSUE THREAD

**Issue by andrejste7** [LBTU-IT-M24/ClassMate#68] opened 2024-10-06 17:14 UTC
### Description
Develop calendar component that would statically show current date of the year without extra options

### TODO
- Implement component described above

**Comment by SandisAbele** [comment] 2024-10-12 12:01
Tested

Looks like all functionality works as intended, styling works as expected, also can add/remove lessons, and those are displayed properly too.

QA pass, closing ticket.

**Closed by SandisAbele** 2024-10-12 12:01 UTC
